# This is an example GitHub Actions workflow that will allow you to build your project with every push or pull request.
# For more information, see:
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions

name: Rust Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make release
      working-directory: ./baseball_crud

    - name: Lint
      run: make lint
      working-directory: ./baseball_crud
    
    - name: Format
      run: make format
      working-directory: ./baseball_crud

    - name: Test
      run: make test
      working-directory: ./baseball_crud

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: baseball_crud_binary
        path: baseball_crud/target/release/baseball_crud

    